BSSudoku := BacktrackingSearch/BSSudoku.cc
ESSudoku := EXhaustiveSearch/ESSudoku.cc
FCSudoku := ForwardChecking/FCSudoku.cc
MRVSudoku := MinimumRemainingValues/MRVSudoku.cc

all:
	g++ main.cc $(BSSudoku) $(ESSudoku) $(FCSudoku) $(MRVSudoku) -o main

run:
	./main